<a href="https://colab.research.google.com/github/689photo/Colab_AI/blob/main/math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
test_array = np.array([[1, 4, 5, 8],[2, 5, 8, 11]], int)
print(test_array)

[[ 1  4  5  8]
 [ 2  5  8 11]]


In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
test_array.transpose()

array([[ 1,  2],
       [ 4,  5],
       [ 5,  8],
       [ 8, 11]])

In [ ]:
x = np.array([1, 7, 2])
y = np.array([5, 2, 1])
x / y

array([0.2, 3.5, 2. ])